import '../../../l10n/app_localizations.dart';
import '../domain/app_settings.dart';

String settingFlagLabel(AppLocalizations s, SettingFlag flag) {
  return switch (flag) {
    SettingFlag.confirmBeforeExit => s.confirmBeforeExit,
    SettingFlag.confirmBeforeResignation => s.confirmBeforeResignation,
    SettingFlag.confirmBeforeSpendingCoins => s.confirmBeforeSpendingCoins,
    SettingFlag.rememberPlayerName => s.rememberPlayerName,
    SettingFlag.boardCoordinates => s.boardCoordinates,
    SettingFlag.lastMoveHighlight => s.lastMoveHighlight,
    SettingFlag.checkHighlight => s.checkHighlight,
    SettingFlag.capturedPieceDisplay => s.capturedPieceDisplay,
    SettingFlag.materialScoreDisplay => s.materialScoreDisplay,
    SettingFlag.moveHistoryDisplay => s.moveHistoryDisplay,
    SettingFlag.reducedMotion => s.reducedMotion,
    SettingFlag.fullScreenGame => s.fullScreenGameMode,
    SettingFlag.watermarkVisible => s.watermarkVisibility,
    SettingFlag.allowLocalUndo => s.allowUndoLocal,
    SettingFlag.confirmUndo => s.confirmUndo,
    SettingFlag.rotateLocalBoard => s.rotateLocalBoard,
    SettingFlag.autoFlipBlack => s.autoFlipBlack,
    SettingFlag.showLegalMoves => s.showLegalMoves,
    SettingFlag.showLastMove => s.showLastMove,
    SettingFlag.hintsEnabled => s.enableHints,
    SettingFlag.confirmHintSpending => s.confirmHintSpending,
    SettingFlag.autoSave => s.autoSaveGame,
    SettingFlag.resumeLastGame => s.resumeLastGame,
    SettingFlag.keepScreenAwake => s.keepScreenAwake,
    SettingFlag.showEvaluation => s.showEvaluation,
    SettingFlag.estimatedMaterialAdvantage => s.estimatedMaterialAdvantage,
    SettingFlag.masterSound => s.masterSound,
    SettingFlag.music => s.music,
    SettingFlag.soundEffects => s.soundEffects,
    SettingFlag.moveSound => s.moveSound,
    SettingFlag.captureSound => s.captureSound,
    SettingFlag.checkSound => s.checkSound,
    SettingFlag.checkmateSound => s.checkmateSound,
    SettingFlag.clockWarningSound => s.clockWarningSound,
    SettingFlag.buttonSounds => s.buttonSounds,
    SettingFlag.rewardSounds => s.rewardSounds,
    SettingFlag.hapticFeedback => s.hapticFeedback,
    SettingFlag.moveHaptic => s.moveHaptic,
    SettingFlag.captureHaptic => s.captureHaptic,
    SettingFlag.warningHaptic => s.warningHaptic,
    SettingFlag.batterySavingEngine => s.batterySavingEngine,
    SettingFlag.backgroundAnalysis => s.backgroundAnalysis,
    SettingFlag.computerThinkingIndicator => s.computerThinkingIndicator,
    SettingFlag.wifiOnlyWarning => s.wifiOnlyWarning,
    SettingFlag.networkDiagnostics => s.showNetworkDiagnostics,
    SettingFlag.dailyReminder => s.dailyReminder,
    SettingFlag.rewardAnimations => s.rewardAnimations,
    SettingFlag.coinBalanceDisplay => s.coinBalanceDisplay,
    SettingFlag.hintBalanceDisplay => s.hintBalanceDisplay,
    SettingFlag.streakDisplay => s.streakDisplay,
    SettingFlag.highContrast => s.highContrast,
    SettingFlag.largerBoardIndicators => s.largerBoardIndicators,
    SettingFlag.strongerLegalMoveMarkers => s.strongerLegalMoveMarkers,
    SettingFlag.announceMoves => s.announceMoves,
    SettingFlag.announceChecks => s.announceChecks,
    SettingFlag.announceTimerWarnings => s.announceTimerWarnings,
    SettingFlag.usePieceNames => s.usePieceNames,
    SettingFlag.useAlgebraicNotation => s.useAlgebraicNotation,
    SettingFlag.hapticAlternatives => s.hapticAlternatives,
    SettingFlag.colorBlindPalette => s.colorBlindPalette,
    SettingFlag.screenReaderBoardMode => s.screenReaderBoardMode,
  };
}

String featureFlagLabel(AppLocalizations s, TypedFeatureFlag flag) {
  return switch (flag) {
    TypedFeatureFlag.experimentalAnalysis => s.showEvaluation,
    TypedFeatureFlag.pseudolocalization => s.pseudolocalization,
    TypedFeatureFlag.debugOverlay => s.debugControls,
    TypedFeatureFlag.performanceOverlay => s.performanceOverlay,
    TypedFeatureFlag.layoutBounds => s.layoutBoundaryVisualization,
    TypedFeatureFlag.repaintRainbowGuidance => s.repaintRainbowGuidance,
    TypedFeatureFlag.stateLogger => s.stateEventLogger,
    TypedFeatureFlag.navigationLogger => s.navigationLogger,
    TypedFeatureFlag.databaseLogger => s.databaseLogger,
    TypedFeatureFlag.engineLogger => s.engineUciLogger,
    TypedFeatureFlag.multiplayerLogger => s.multiplayerProtocolLogger,
    TypedFeatureFlag.localizationKeyViewer => s.localizationKeyViewer,
    TypedFeatureFlag.accessibilityLabelViewer => s.accessibilityLabelViewer,
    TypedFeatureFlag.expandedTextPreview => s.expandTextLength,
    TypedFeatureFlag.rtlPreview => s.rtlPreview,
  };
}
